#!/bin/bash

# Quick Demo Script - Show project structure and test web interface

echo "╔══════════════════════════════════════════════════════════╗"
echo "║        🧬 AI Drug Discovery - Quick Demo                ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""

echo "📁 Project Structure:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🎨 FRONTEND (Web Interface):"
echo "   ├── templates/index.html     - Beautiful web UI"
echo "   └── static/                  - CSS/JS/Images"
echo ""
echo "⚙️  BACKEND (API + ML Models):"
echo "   ├── app.py                   - Flask REST API"
echo "   └── src/                     - ML Pipeline"
echo "       ├── data/                - Data processing"
echo "       ├── models/              - Model training"
echo "       └── utils/               - Helpers"
echo ""
echo "💾 DATASET:"
echo "   └── data/"
echo "       ├── raw/drug_data.csv    - 10,000 samples"
echo "       └── sample_drugs.json    - 10 test cases"
echo ""
echo "🧠 TRAINED MODELS:"
echo "   └── models/"
echo "       ├── best_model.pkl       - XGBoost (88-90%)"
echo "       └── model_metrics.json   - Accuracy stats"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Check files exist
echo "🔍 Checking Files:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

check_file() {
    if [ -f "$1" ]; then
        echo "✅ $2"
    else
        echo "❌ $2 (missing)"
    fi
}

check_dir() {
    if [ -d "$1" ]; then
        echo "✅ $2"
    else
        echo "❌ $2 (missing)"
    fi
}

check_file "app.py" "Backend API (app.py)"
check_file "templates/index.html" "Frontend UI (templates/index.html)"
check_file "data/sample_drugs.json" "Sample Test Cases (10 drugs)"
check_file "data/raw/drug_data.csv" "Training Dataset (10,000 samples)"
check_dir "src" "ML Source Code (src/)"
check_dir "models" "Trained Models (models/)"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Show sample test case
echo "📋 Sample Test Case (Drug F - Best Performance):"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Input Values:"
echo "  • Molecular Weight: 325.4"
echo "  • LogP: 3.8"
echo "  • Efficacy Score: 9.0"
echo "  • Safety Score: 8.5"
echo "  • Hepatotoxicity: 1.5"
echo "  • Cardiotoxicity: 1.2"
echo "  • Nephrotoxicity: 1.0"
echo "  • Binding Affinity: -9.5"
echo "  • Bioavailability: 0.92"
echo "  • Absorption Rate: 0.92"
echo ""
echo "Expected Result:"
echo "  🟢 HIGHLY EFFECTIVE (90-95% Confidence)"
echo "  🟢 LOW Risk"
echo "  ✅ Recommendation: PROCEED TO CLINICAL TRIALS"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Show all 10 samples
echo "📊 All 10 Test Cases:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo " #  │ Drug Name                    │ Expected Result"
echo "────┼──────────────────────────────┼─────────────────────────"
echo " 1  │ High Efficacy Antibiotic     │ HIGHLY EFFECTIVE (85-90%)"
echo " 2  │ Moderate Cardiovascular      │ EFFECTIVE (70-80%)"
echo " 3  │ High Toxicity Compound       │ NOT RECOMMENDED (Toxic)"
echo " 4  │ Poor Bioavailability         │ NOT EFFECTIVE (Low)"
echo " 5  │ Balanced Cancer Drug         │ EFFECTIVE (75-85%)"
echo " 6  │ Excellent CNS Drug ⭐        │ HIGHLY EFFECTIVE (90-95%)"
echo " 7  │ Moderate Anti-inflammatory   │ MODERATE (65-75%)"
echo " 8  │ Failed Candidate             │ NOT EFFECTIVE (Failed)"
echo " 9  │ Promising Antiviral          │ HIGHLY EFFECTIVE (88-92%)"
echo " 10 │ Borderline Case              │ MODERATE (60-70%)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Instructions
echo "🚀 How to Run:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Step 1: Start Web Server"
echo "  bash start_web.sh"
echo ""
echo "  OR manually:"
echo "  python3 app.py"
echo ""
echo "Step 2: Open Browser"
echo "  http://127.0.0.1:5000"
echo ""
echo "Step 3: Test the System"
echo "  • Click 'Load Sample Drug'"
echo "  • Select any drug (try Drug F first!)"
echo "  • Click 'Predict'"
echo "  • See results with visualizations!"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Features
echo "✨ Web Interface Features:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ Beautiful gradient UI design"
echo "✅ Real-time predictions (<1 second)"
echo "✅ Animated probability bars"
echo "✅ Color-coded results (Green/Yellow/Red)"
echo "✅ Risk assessment visualization"
echo "✅ 10 ready-to-use test cases"
echo "✅ One-click sample loading"
echo "✅ Model accuracy dashboard"
echo "✅ Clinical recommendations"
echo "✅ Responsive mobile-friendly design"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Documentation
echo "📚 Documentation Files:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. QUICK_ANSWER.md          - Quick reference (Bengali)"
echo "2. WEB_FRONTEND_GUIDE.md    - Complete web guide"
echo "3. BANGLA_GUIDE.md          - Full Bengali documentation"
echo "4. PRESENTATION_REPORT.md   - Academic presentation"
echo "5. README.md                - English documentation"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "🎯 Quick Start Command:"
echo ""
echo "  bash start_web.sh"
echo ""
echo "Then open: http://127.0.0.1:5000"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ Everything is ready! Start the web server to begin."
echo ""
echo "╚══════════════════════════════════════════════════════════╝"
